name: test diagram

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: update 
      uses: actions/repo-visualizer@main
      with:
        output_file: diagram
        should_push: false
  
    - uses: actions/artifact@v4
      with:
        name: diagram
        path: diagram.svg
